type dayNumbers=string #day0=sunday,day1=monday,...

# the chrome local storage
# its a mess of things
type chromeStorage
{
    [showId]:ShowObject, #show IDS mapped to their respective show objects

    [dayNumbers]:ShowDict, #ids for each day, from day0 to day7, mapped to ShowDicts

    ids:ShowIDsObject, #object containing hopefully all the ids of the shows

    userOps:[string,string] #string array holding usernames which apparently there can be 2 of
}

# contains show information
type ShowObject
{
    cover:string,
    day:string,
    id:int,
    link:url, # anilist url
    nyaa:string,
    progress:int,
    title:string
}

# a set of show ids stored as an object, so the key is meaningless.
# used to indicate which showIDs are in a day
type ShowDict
{
    [showId]:string
}

# contains unique show IDs so they can be accessed from the main local storage
# without having to loop through. each ID is mapped to possibly the episode count
# of the show, but might not be accurately updated
type ShowIDsObject
{
    [showId]:int
}