# retrieve shows of a target user.
# returns UserShowsQueryResult
query($userName:String)
{
    MediaListCollection(
        userName:$userName,
        type:ANIME,
        status:CURRENT
    )
    {
        lists {
            name
            entries {
                progress
                media {
                    title {
                        romaji
                    }

                    coverImage {
                        large
                    }

                    id
                    siteUrl
                }
            }
        }
    }
}